version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: info-retrieval-frontend
    ports:
      - 80:80
    depends_on:
      - rest-api
      - elasticsearch
      - mongo
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cat/health?h=st || exit 1",
        ]
      interval: 50s
      timeout: 30s
      retries: 5
    environment:
      - cluster.name=movies-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200
  rest-api:
    container_name: rest-api
    build:
      context: ./info-retrieval-rest
    ports:
      - 3000:3000
    env_file:
      - ./environments/rest-api.env
    depends_on:
      - mongo
      - elasticsearch
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
